theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Real-Time HAR using mmwave Radar
description: Project for UCLA ECEM202A/CSM213A (Fall 2022)
